print(" ________________________________")
print("|                                |")
print("|   Aldo     | 7 marzo 1990      |")
print("|   Giacomo  | 18 agosto 1992    |")
print("|   Giovanni | 15 settembre 2000 |")
print("|   Sabrina  | 22 dicembre 1995  |")
print("|________________________________|")
